# Laboratorio 9
## Andres Gálvez - 1024718

# 3.1

In [1]:
import numpy as np

np.random.seed(2131982)
data = np.random.randint(1, 101, size = (10, 10))
print(data)
print("Media aritmética: " + str(data.mean()))
print("Mediana: " + str(np.median(data)))
print("Desviación típica: " + str(data.std()))
print("Varianza: " + str(data.var()))
print("Media aritmética por cada fila: " + str(data.mean(axis = 1)))
print("Media aritmética por cada columna: " + str(data.mean(axis = 0)))
print("Desviación típica por cada fila: " + str(data.std(axis = 1)))
print("Desviación típica por cada columna: " + str(data.std(axis = 0)))
print("Varianza por cada fila: " + str(data.var(axis = 1)))
print("Varianza por cada columna: " + str(data.var(axis = 0)))

import pandas as pd

dataframe = pd.DataFrame(data, columns = ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10'])
dataframe.describe()

[[  2   3  48  59  89  79  71  80  19  22]
 [ 74  20  16  13  74  88  61  28  11  79]
 [ 86  91  91  80  43   6  83  59 100  98]
 [ 38  37  47  48  15  17  21   6  32  88]
 [ 14  18  54  39  47  48  33  59  63  49]
 [ 98  19  59  99  26  42  77  62  25  11]
 [ 42  25  16  66   6  76  84  20  11  95]
 [  9  27  63  24  15  73  44  22  47  85]
 [ 58  37  94  24  99  70  39  46  29 100]
 [ 98  92  91  24  70  91  78  73  73  37]]
Media aritmética: 51.37
Mediana: 48.0
Desviación típica: 29.729330634913392
Varianza: 883.8331
Media aritmética por cada fila: [47.2 46.4 73.7 34.9 42.4 51.8 44.1 40.9 59.6 72.7]
Media aritmética por cada columna: [51.9 36.9 57.9 47.6 48.4 59.  59.1 45.5 41.  66.4]
Desviación típica por cada fila: [31.57150614 29.76306436 28.10711654 22.14700883 15.59615337 30.61633551
 31.57039753 24.56603346 27.93277645 23.16052676]
Desviación típica por cada columna: [34.6365414  28.83556831 26.95347844 26.65032833 31.45218593 28.02498885
 21.86069532 23.77498686 27.91057147 3

c1         c2         c3         c4         c5         c6  \
count  10.00000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   51.90000  36.900000  57.900000  47.600000  48.400000  59.000000   
std    36.51012  30.395358  28.411461  28.091913  33.153515  29.540932   
min     2.00000   3.000000  16.000000  13.000000   6.000000   6.000000   
25%    20.00000  19.250000  47.250000  24.000000  17.750000  43.500000   
50%    50.00000  26.000000  56.500000  43.500000  45.000000  71.500000   
75%    83.00000  37.000000  84.000000  64.250000  73.000000  78.250000   
max    98.00000  92.000000  94.000000  99.000000  99.000000  91.000000   

              c7         c8          c9         c10  
count  10.000000  10.000000   10.000000   10.000000  
mean   59.100000  45.500000   41.000000   66.400000  
std    23.043196  25.061037   29.420326   33.540026  
min    21.000000   6.000000   11.000000   11.000000  
25%    40.250000  23.500000   20.500000   40.000000  
50%    66.000000  52.500000   30.500000   82.000000  
75%    77.750000  61.250000   59.000000   93.250000  
max    84.000000  80.000000  100.000000  100.000000

Coincidencia de datos, salvo std.

# 3.2

In [2]:
import pyAgrum as gum

bn = gum.BayesNet()
b, e, a, j, m = [bn.add(name, 2) for name in "beajm"]
bn.addArc(b, a)
bn.addArc(e, a)
bn.addArc(a, j)
bn.addArc(a, m)

In [3]:
bn.cpt(b).fillWith([0.999, 0.001])

(gum::Potential<double>@000001AE5DBD5470) 
  b                |
0        |1        |
---------|---------|
 0.9990  | 0.0010  |

In [4]:
bn.cpt(e).fillWith([0.998, 0.002])

(gum::Potential<double>@000001AE5DBD5330) 
  e                |
0        |1        |
---------|---------|
 0.9980  | 0.0020  |

In [5]:
bn.cpt(a)[{'b': 0, 'e': 0}] = [0.999, 0.001]
bn.cpt(a)[{'b': 0, 'e': 1}] = [0.71, 0.29]
bn.cpt(a)[{'b': 1, 'e': 0}] = [0.06, 0.94]
bn.cpt(a)[{'b': 1, 'e': 1}] = [0.05, 0.95]
bn.cpt(j)[:] = [[0.95, 0.05], [0.1, 0.9]]
bn.cpt(m)[:] = [[0.99, 0.01], [0.3, 0.7]]

In [15]:
import pyAgrum.lib.notebook as gnb
bn

(gum::BayesNet<double>@000001AE75091ED0) BN{nodes: 5, arcs: 4, domainSize: 32, dim: 20}

In [7]:
ie = gum.LazyPropagation(bn)

* $P(+b, -e, +a, -j, +m)$
  * $P(+b)P(-e)P(+a|+b,-e)P(-j|+a)P(+m|+a)$

In [8]:
ie.setEvidence({'b': 1, 'e': 0})
ie.makeInference()
Pa = ie.posterior(a)[1]

In [9]:
ie.setEvidence({'a': 1})
ie.makeInference()
Pj = ie.posterior(j)[0]

In [10]:
ie.setEvidence({'a': 1})
ie.makeInference()
Pm = ie.posterior(m)[1]

In [11]:
bn.cpt(b)[1] * bn.cpt(e)[0] * Pa * Pj * Pm

6.56684e-05

* $P(M)$

In [12]:
ie.makeInference()
print(ie.posterior(m))


  m                |
0        |1        |
---------|---------|
 0.3000  | 0.7000  |



* $P(M|+b, +a)$ <br/>
Variables
* H: e
* Q: M
* E: b, a

In [13]:
ie.setEvidence({'b': 1, 'a': 1})
ie.makeInference()
print(ie.posterior(m))


  m                |
0        |1        |
---------|---------|
 0.3000  | 0.7000  |

